### ISSUE TITLE
setting not saved and can't add additional sprites on linux

### ISSUE THREAD

**Issue by jenningsloy318** [LLK/scratch-desktop#540]
### Expected Behavior
1. the language settign should preserve after reboot 
2. we can add additional sprites

### Actual Behavior

1. when i change the language, then after that closed the app and launch it again, the language fall back to English again
2. when programming, want to add a second sprite, it open page to choose the second sprite. on the one hand, these sprite are not loaded, and also when any click is selected, return to main page, there still only one sprite

### Steps to Reproduce

1. when i change the language, then after that closed the app and launch it again, the language fall back to English again
2. when programming, want to add a second sprite, it open page to choose the second sprite. on the one hand, these sprite are not loaded, and also when any click is selected, return to main page, there still only one sprite

### System Details
debian 13 
nodejs 22 

**Screenshots**

<img width="1288" height="841" alt="Image" src="https://github.com/user-attachments/assets/5262f2a9-6976-4489-bc3e-d044bb6f3e7e" />

**Comment by heidaren0000** [comment]
That's a bug in scratch-gui, I fixed it by update the package.

```
    "@scratch/scratch-gui": "11.6.0",
```

And language setting probably picked up from environment variables

**Comment by jenningsloy318** [comment]
still not working,  seems the real issue is that all images for these spirates are not loaded. 

and I executed the cli from terminal, but there is not errors

**Comment by heidaren0000** [comment]
> still not working, seems the real issue is that all images for these spirates are not loaded.
> 
> and I executed the cli from terminal, but there is not errors

Here's my build if you need. 
However I've noticed some minor issue when saving project (the saving dialog prompts 2 times on my Plasma 6, but it still works.) 

https://drive.google.com/file/d/1AASA2esvRWiqldL_5Qt2m2zDdVDvCkVd/view?usp=sharing

**Comment by jenningsloy318** [comment]
Your build is working, thank you very much.

And can you share the build process and command you used?  i followed the same build process, why not working.

**Comment by heidaren0000** [comment]
> Your build is working, thank you very much.
> 
> And can you share the build process and command you used?  i followed the same build process, why not working. 

I'm not sure what happened in your case.
All I did is just update the npm package.

**Comment by jenningsloy318** [comment]
I just found that i only run `npm run dist:build` instead of `npm run dist`, now my build is also working. 

thank you.
